### ISSUE TITLE
启动项目报错：  Error: spawn babel-node ENOENT

### ISSUE THREAD

**Issue by sunscheung** [HiJesse/Demeter#1]
Error: spawn babel-node ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

**Comment by sunscheung** [comment]
@HiJesse

**Comment by HiJesse** [comment]
@sunscheung 你的系统, nodejs 版本分别是什么?

**Comment by sunscheung** [comment]
windows 7 64位系统
nodejs 6.10.1
@HiJesse

**Comment by sunscheung** [comment]
@HiJesse

**Comment by HiJesse** [comment]
@sunscheung 我的nodejs 版本是 v7.2.1. 你在release分支构建吧. 我没有在windows平台跑过.
